version: "2.10.2"

services:

  env_file : .env

  mariadb:

    build:
      context: ./requirements/mariadb
    
    volumes:
      - ./requirements/mariadb/data/mysql:/var/lib/mysql

    ports:
      - "3306"

    networks:
      - inception

    restart: "always"

  nginx:

    build: 
      context: ./requirements/nginx/

      depends_on:
        - wordpress

    ports: 
      - "443"
    
    networks:
      - inception

    restart: "always"
  
  wordpress:

    build:
      context: ./requirements/wordpress
    
    depends_on:
      - mariadb
    
    ports:
      - "9000"

    networks:
      - inception

    restart: "always"

  networks:
    inception: