version: "3.3"

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        MB_DATABASE: ${MB_DATABASE}
        MB_ADMIN_USER: ${MB_ADMIN_USER}
        MB_ADMIN_PASSWORD: ${MB_ADMIN_PASSWORD}
        MB_ROOT_PASSWORD: ${MB_ROOT_PASSWORD}
    volumes:
      - mdb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception
    restart: "always"
    env_file:
      - .env

  nginx:
    build: 
      context: ./requirements/nginx/
    depends_on:
      - wordpress
    ports: 
      - "443:443"
    networks:
      - inception
    restart: "always"
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
  
  wordpress:
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - inception
    restart: "always"
    env_file:
      - .env
    volumes:
      - wp:/var/www/html

networks:
  inception:

volumes:
  mdb:
    driver_opts:
      type: none
      device: /home/naben-za/data/
      o: bind
  wp:
    driver_opts:
      type: none
      device: /home/naben-za/data/
      o: bind