version: "2.12"

services:

  mariadb:

    build:
      context: ./requirements/mariadb
    
    volumes:
      - ./requirements/mariadb/data/mysql:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    restart: ""

  # wordpress:

  #   build:
  #     context: ./requirements/wordpress

  nginx:

    build: 
      context: ./requirements/nginx/

    ports: 
      - "8080:80"

    restart: ""
